version: "3.3"

networks:
  net:
    driver: bridge

services:
  #--------------  PROJECT APP --------------
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile_l4t-ml #Dockerfile_dli_nano #

    image: ${APP_IMG_BUILDER}:${VERSION}
    container_name: '${APP_CNTNR_NAME}'
    environment:
      - APP_SERVER_PORT=${APP_SERVER_PORT}

    ports:
      - '${APP_HOST_PORT}:${APP_SERVER_PORT}'
      
    networks:
      - net
    # network_mode: host

    volumes: 
      - './artifacts:/app/artifacts'
      # - './config:/app/config'
      - './data:/app/data'
    command: 'python src/main.py'


