### list of nvidia containers: https://catalog.ngc.nvidia.com/containers 
# ARG BASE_IMAGE=nvcr.io/nvidia/dli/dli-nano-ai:v2.0.2-r32.7.1
# ARG BASE_IMAGE=nvcr.io/nvidia/l4t-base:r32.7.1
# ARG BASE_IMAGE=dustynv/jetson-inference:r32.7.1

# # https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-22-12.html
# ARG BASE_IMAGE=nvcr.io/nvidia/pytorch:20.11-py3  

# ##TensorRT:https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorrt/tags
# ARG BASE_IMAGE=nvcr.io/nvidia/tensorrt:24.10-py3-igpu

## Jetson Nano Image: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-base/tags
ARG BASE_IMAGE=nvcr.io/nvidia/l4t-ml:r32.5.0-py3

##---------------------------------------------------------------------------
FROM ${BASE_IMAGE}

ARG APP_SERVER_PORT=8080

RUN apt update -y && apt install awscli -y

# copy the code files
WORKDIR /app
COPY src /app/src
COPY src/requirements.txt .
COPY src/setup.py .
COPY src/README.md .

# install the packages
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

CMD ["python3", "src/main.py"]