ARG BASE_IMAGE=nvcr.io/nvidia/dli/dli-nano-ai:v2.0.2-r32.7.1

##---------------------------------------------------------------------------
FROM ${BASE_IMAGE}

ARG APP_SERVER_PORT=8080

# copy the code files
WORKDIR /app
COPY src /app/src
COPY src/requirements.txt .
COPY src/setup.py .
COPY src/README.md .


# Build the environnement
RUN ls -l
RUN pip3 install --no-cache-dir --upgrade -r requirements.txt

EXPOSE $APP_SERVER_PORT
CMD ["python", "src/main.py"]
# CMD ["uvicorn", "webserver:app", "--host", "0.0.0.0", "--port", "${WEBAPP_SERVER_PORT}"]